
[colors.primary]
background = "#080808"
foreground = "#e5e8e6"

[env]
TERM = "xterm-256color"

[font]
size = 19

[font.normal]
family = "MesloLGM Nerd Font Mono"
style = "Regular"

[window]
decorations = "buttonless"
opacity = 0.9
option_as_alt = "Both"

[window.padding]
x = 10
y = 10

[general]
live_config_reload = true

import = [ "~/.config/alacritty/themes/themes/Cobalt2.toml" ]
